### PR TITLE
Prep for 0.5 release

### PR DESCRIPTION
**Pull request by sqrrrl**
Updates to release 0.5 for the user authorizer functionality.

Includes updates to tests to use webmock instead of Faraday stubs. Using faraday's stubs turns out to be fragile as data isn't fully normalized (content of env changes depending on the style of the call, even if they're semantically equivalent.) Using webmock ends up being simpler and safer anyway.

### CODE REVIEW

**Comment by tbetbetbe** [comment]
LGTM - thanks!

**Comment by sqrrrl** [comment]
RBX error appears unrelated (seems a lot of people have issues with rubocop being flakey with rubinius - should just be disabled IMHO)

And not going to sweat a -.06% change in code coverage :)

**Comment by tbetbetbe** [comment]
LGTM.

rbx-2 should not trigger a failure; I looks like the [.travis.yml](https://github.com/google/google-auth-library-ruby/blob/master/.travis.yml) should stop that, but does not.  I think the allow_failures should be:

```
matrix:
  allow_failures:
    - rvm: rbx-2 # See rubinius/rubinius#3485 - rubocop segfaults
```

rather than 

```
matrix:
  allow_failures:
    - rbx-2 # See rubinius/rubinius#3485 - rubocop segfaults
```

Can you add that to this PR and see if it makes a difference ?

**Comment by sqrrrl** [comment]
Thanks, that did the trick.

**Pull request merged**
